vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("let g:loaded_matchparen=1")
vim.cmd("set relativenumber")
vim.cmd("set number")
vim.cmd("set signcolumn=yes")
vim.cmd("set guicursor=n-v-c-i:block")
vim.g.mapleader = " "

vim.cmd("nmap <leader>e :Lexplore<CR>")
vim.cmd("let g:netrw_keepdir = 0")
vim.cmd("let g:netrw_banner = 0")
vim.cmd("let g:netrw_winsize = 20")
vim.cmd("let g:netrw_localcopydircmd = 'cp -r'")
